In [1]:
'''
Copyright 2015 Matthew Loper, Naureen Mahmood and the Max Planck Gesellschaft.  All rights reserved.
This software is provided for research purposes only.
By using this software you agree to the terms of the SMPL Model license here http://smpl.is.tue.mpg.de/license

More information about SMPL is available here http://smpl.is.tue.mpg.
For comments or questions, please email us at: smpl@tuebingen.mpg.de


Please Note:
============
This is a demo version of the script for driving the SMPL model with python.
We would be happy to receive comments, help and suggestions on improving this code 
and in making it available on more platforms. 


System Requirements:
====================
Operating system: OSX, Linux

Python Dependencies:
- Numpy & Scipy  [http://www.scipy.org/scipylib/download.html]
- Chumpy [https://github.com/mattloper/chumpy]


About the Script:
=================
This script demonstrates a few basic functions to help users get started with using 
the SMPL model. The code shows how to:
  - Load the SMPL model
  - Edit pose & shape parameters of the model to create a new body in a new pose
  - Save the resulting body as a mesh in .OBJ format


Running the Hello World code:
=============================
Inside Terminal, navigate to the smpl/webuser/hello_world directory. You can run 
the hello world script now by typing the following:
>	python hello_smpl.py

'''

'\nCopyright 2015 Matthew Loper, Naureen Mahmood and the Max Planck Gesellschaft.  All rights reserved.\nThis software is provided for research purposes only.\nBy using this software you agree to the terms of the SMPL Model license here http://smpl.is.tue.mpg.de/license\n\nMore information about SMPL is available here http://smpl.is.tue.mpg.\nFor comments or questions, please email us at: smpl@tuebingen.mpg.de\n\n\nPlease Note:\n============\nThis is a demo version of the script for driving the SMPL model with python.\nWe would be happy to receive comments, help and suggestions on improving this code \nand in making it available on more platforms. \n\n\nSystem Requirements:\n====================\nOperating system: OSX, Linux\n\nPython Dependencies:\n- Numpy & Scipy  [http://www.scipy.org/scipylib/download.html]\n- Chumpy [https://github.com/mattloper/chumpy]\n\n\nAbout the Script:\n=================\nThis script demonstrates a few basic functions to help users get started with using \n

In [3]:
import os

print(os.getcwd())
os.chdir(r'D:\Coding\bodies-at-rest')
print(os.getcwd())

D:\Coding\bodies-at-rest
D:\Coding\bodies-at-rest


In [26]:
from smpl.smpl_webuser.serialization import load_model
import numpy as np

## Load SMPL model (here we load the female model)
## Make sure path is correct
m = load_model(r'smpl\models\basicModel_f_lbs_10_207_0_v1.0.0.pkl')


print(f"model.shape: {m.shape}")
methods_and_properties = dir(m)
print(methods_and_properties)

print(f"m is a {type(m)}")

model.shape: (6890, 3)
['J', 'J_regressor', 'J_regressor_prior', 'J_transformed', 'T', '__abs__', '__add__', '__array__', '__array_priority__', '__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__float__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__int__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__rpow__', '__rsub__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '_cache', '_cached_parms', '_call_on_changed', '_compute_dr_wrt_sliced', '_default_kwargs', '_depends_on_deps', '_dirty_vars', '_invalidate_cacheprop_names', '_itr', '_make_dense', '_make_sparse', '_parents', '_reserved_kw', '_setup_terms', '_status'

In [46]:
# set numpy to print only 2 decimal digits with fixed point notation
np.set_printoptions(precision=2, suppress=True)

import numpy as np
from scipy.spatial.transform import Rotation as R

# Define the rotation vector: [0, 0, π/2]
rotation_vector = np.array([0, 0, np.pi])
print(f'rotation_vector: {rotation_vector}')

# Convert the rotation vector to a rotation matrix
rotation_matrix = R.from_rotvec(rotation_vector).as_matrix()
print(f'rotation_matrix:')
print(rotation_matrix)

# Define a point to rotate
point = np.array([1, 0, 0])
print(f'point: {point}')

# Rotate the point
rotated_point = rotation_matrix.dot(point)
print(f'rotated_point: {rotated_point}')

rotation_vector: [0.   0.   3.14]
rotation_matrix:
[[-1. -0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
point: [1 0 0]
rotated_point: [-1.  0.  0.]


In [55]:
rotation_vector = np.array([0, np.pi, 0])
print(f'rotation_vector: {rotation_vector}')

rotation_matrix = R.from_rotvec(rotation_vector).as_matrix()
print(f'rotation_matrix:')
print(rotation_matrix)

point = np.array([1, 0, 0])
print(f'point: {point}')

rotated_point = rotation_matrix.dot(point)
print(f'rotated_point: {rotated_point}')

# help(R)

rotation_vector: [0.   3.14 0.  ]
rotation_matrix:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0. -1.]]
point: [1 0 0]
rotated_point: [-1.  0. -0.]


In [61]:
m_pose = np.random.rand(m.pose.size)
m_betas = np.random.rand(m.betas.size)

print(f"m_pose: {m_pose.shape}, {m.pose.shape}")
print(f"m_betas: {m_betas.shape}, {m.betas.size}")

m_pose: (72,), (72,)
m_betas: (10,), 10


In [67]:
## Assign random pose and shape parameters
m.pose[:] = np.random.rand(m.pose.size) * .2
m.betas[:] = np.random.rand(m.betas.size) * .03

## Write to an .obj file
outmesh_path = './hello_smpl.obj'
with open( outmesh_path, 'w') as fp:
    for i, v in enumerate(m.r):
        fp.write( 'v %f %f %f\n' % ( v[0], v[1], v[2]) )
        print(f'v ({i}): {v[0]:.2f} {v[1]:.2f} {v[2]:.2f}')

    for j, f in enumerate(m.f+1): # Faces are 1-based, not 0-based in obj files
        fp.write( 'f %d %d %d\n' %  (f[0], f[1], f[2]) )
        print(f'f ({j}): {f[0]} {f[1]} {f[2]}')

## Print message
print('..Output mesh saved to: ', outmesh_path)

v (0): -0.11 0.34 0.39
v (1): -0.10 0.33 0.39
v (2): -0.10 0.33 0.38
v (3): -0.11 0.35 0.37
v (4): -0.09 0.32 0.38
v (5): -0.10 0.32 0.39
v (6): -0.10 0.33 0.36
v (7): -0.10 0.35 0.36
v (8): -0.09 0.32 0.33
v (9): -0.09 0.32 0.32
v (10): -0.09 0.32 0.33
v (11): -0.09 0.32 0.34
v (12): -0.08 0.30 0.32
v (13): -0.07 0.28 0.32
v (14): -0.08 0.28 0.31
v (15): -0.08 0.29 0.30
v (16): -0.09 0.27 0.36
v (17): -0.08 0.27 0.35
v (18): -0.08 0.27 0.35
v (19): -0.09 0.27 0.36
v (20): -0.09 0.27 0.37
v (21): -0.10 0.27 0.37
v (22): -0.10 0.27 0.38
v (23): -0.10 0.27 0.38
v (24): -0.09 0.26 0.36
v (25): -0.08 0.26 0.35
v (26): -0.09 0.27 0.36
v (27): -0.09 0.26 0.36
v (28): -0.09 0.25 0.37
v (29): -0.09 0.26 0.37
v (30): -0.09 0.26 0.37
v (31): -0.08 0.25 0.37
v (32): -0.09 0.26 0.36
v (33): -0.09 0.26 0.36
v (34): -0.09 0.26 0.36
v (35): -0.09 0.25 0.36
v (36): -0.09 0.26 0.37
v (37): -0.09 0.26 0.38
v (38): -0.09 0.26 0.38
v (39): -0.08 0.25 0.38
v (40): -0.07 0.27 0.34
v (41): -0.08 0.27 0.34
v 

In [29]:
print(f"m help: {help(m)}")

Help on add in module chumpy.ch_ops object:

class add(chumpy.ch.Ch)
 |  add(*args, **kwargs)
 |  
 |  Method resolution order:
 |      add
 |      chumpy.ch.Ch
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  compute_dr_wrt(self, wrt)
 |      Default method for objects that just contain a number or ndarray
 |  
 |  compute_r(self)
 |      Default method for objects that just contain a number or ndarray
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  dterms = ('a', 'b')
 |  
 |  term_order = ['a', 'b']
 |  
 |  terms = []
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from chumpy.ch.Ch:
 |  
 |  __abs__(self)
 |  
 |  __add__(self, other)
 |  
 |  __array__(self, *args)
 |  
 |  __call__(self, **kwargs)
 |      Call self as a function.
 |  
 |  __div__(self, other)
 |  
 |  __float__(self)
 |  
 |  __ge__(self, other)
 |      Return 